### ISSUE TITLE
Report is generated without any test results, only blank report is generated

### ISSUE THREAD

**Issue by nanthakumarv** [paypal/nemo-accessibility#13]
hi @mpnkhan ,

@nikulkarni 

Please reply Sir. This is the final step of implementing this AATT in our project. If you can help it will be really helpful for me to use this AATT.

After scanning is done, report is getting generated, but there is nothing inside the report. While launching the report it says "Unable to load the address"

Used browser:chrome and engine:chrome

$ DEBUG=nemo* node example/usingNemoAccessibility.js
  nemo:log new Nemo instance created +0ms
  nemo:log constructor: basedir + callback +3ms
  nemo:log confit options { protocols:
   { path: [Function: pathHandler],
     env: [Function: envHandler],
     argv: [Function: argHandler] },
  basedir: 'C:\\Users\\391533\\nemo-accessibility\\example\\config' } +1ms
  nemo:log register plugin nemo-accessibility +30ms
  nemo:log modulePath nemo-accessibility +0ms
  nemo:log register plugin view +145ms
  nemo:log modulePath nemo-view +0ms
  nemo:log new Setup instance created +44ms
  nemo:log entering doSetup +1ms
  nemo:log Capabilities { caps_: { browserName: 'chrome' } } +1ms
  nemo:log builder FINAL { flow_: null,
  url_: '',
  proxy_: null,
  capabilities_: { caps_: { browserName: 'chrome' } },
  chromeOptions_: null,
  firefoxOptions_: null,
  operaOptions_: null,
  ieOptions_: null,
  safariOptions_: null,
  ignoreEnv_: false } +0ms
  nemo-view:log plugin setup is called +3s
  nemo-view:log creating Locreator instance +1ms
  nemo-view:log adding generic methods +0ms
Nemo initialized successfully
  nemo-accessibility:log Now scanning with error level  +0ms 1,2,3
  nemo-accessibility:log Accessibility url  +1ms http://127.0.0.1:80/evaluate
Successfully wrote the file C:\Users\391533\nemo-accessibility\example\defaultOptions.html

But there is nothing in the file.

If i used the engine: htmlcs option, socket gets hanged up.

**Comment by mpnkhan** [comment]
Looks like there is some problem with your environment setup. Check if PhantomJS  and npm are the latest versions. 
Does  http://127.0.0.1:80/ show home page? Click SniffHTML and try entering input field without label. Does it show result?

**Comment by nanthakumarv** [comment]
Thanks a lot @mpnkhan Sir for the reply. I tried what you have instructed.

When i launch the http://127.0.0.1:80/ , i am able to see the home page of AATT.
When i give for example: www.gmail.com in the test URL field and check for the results, i am getting the scanned results.

When i dont give an URL and hit test page, i am getting the error "Unable to load the address" which is the same error I am getting when the report is generated. So i think the scanning is not being done on the URL given in the code.

My phantomJS version is 2.1.7
and my npm version is 3.8.6

Can you please let me know what exactly should be given in the module field in side the config file? What path should be given for the module? Is it nemo-accessibility or some path to it? 

I have attached the screenshots for reference.
![nemo-accessibility_2_screenshot](https://cloud.githubusercontent.com/assets/20418065/24091470/4427e5ea-0d6e-11e7-9d74-93a9cd45f5e6.png)
![nemo-accessibility_1_screenshot](https://cloud.githubusercontent.com/assets/20418065/24091479/4e44af9a-0d6e-11e7-8a0f-36b74320c3f7.png)

Thanks a lot in advance,
Vithushini

**Comment by mpnkhan** [comment]
click testHTML and paste the html source code.  nemo-plugin sends source code to this API.

**Comment by nanthakumarv** [comment]
hi @mpnkhan ,

Yeah i did that too, and it is working for me.
![nemo-accessibility_3_screenshot](https://cloud.githubusercontent.com/assets/20418065/24093357/6f487e82-0d79-11e7-84e3-b59358d7d400.png)


In my config file, i have given as below:

{
  "driver": {
    "browser": "firefox"
  },
  "plugins": {
    "nemo-accessibility": {
      "module": "**D:\\nemo-accessibility**", ////**What should be given here actually**???
      "arguments": ["http://127.0.0.1:80/evaluate"]
    },
    "view": {
      "module": "nemo-view"
    }    
  }
}

And in my options inside the test file, i have given 
 var options = {
      'priority': ['P1', 'P2', 'P3'],
    'engine':'chrome'
    };

Since if i give engine as htmlcs, the socket hang error message is displayed. Only for chrome engine the report is getting generated.

Thanks,
Vithushini

**Comment by mpnkhan** [comment]
There is no such module for plugins. 
my config.json:
{
  "driver": {
    "browser": "chrome"
  },
  "plugins": {
    "nemo-accessibility": {
      "module": "path:../",
      "arguments": ["http://127.0.0.1:80/evaluate"]
    },
    "view": {
      "module": "nemo-view"
    }    
  }
}

Also don't pass any options to start with. Test with examples. 
https://github.com/paypal/nemo-accessibility/blob/master/example/usingNemoAccessibility.js
https://github.com/paypal/nemo-accessibility/blob/master/example/dynamicpage.js

**Comment by nanthakumarv** [comment]
Thanks @mpnkhan 

Sorry for the trouble again, but i tried with the code exactly given in the Git. But i am getting a socket hangup error as shown in the gitbash screenshot below. Only if i provide the engine as Chrome, it is generating the report without any content. Is there anything that i can do to get the report using the default htmlcs given in the code itself.

Any specific firefox browser version that is required for this to run??

For the URL field in the given screenshot it is showing null value, should we expect our URL which is being launched to be present in that field? I have a doubt as to whether this page is getting scanned or an empty page is being scanned as we get an Unable to load address in the report being generated using chrome engine.

![nemo-accessibility_4_screenshot](https://cloud.githubusercontent.com/assets/20418065/24100226/3e6ccf3c-0d99-11e7-9f1b-0dec78ad803d.png)

Thanks a lot in advance,
Vithu

**Comment by nanthakumarv** [comment]
hi @mpnkhan ,

Any suggestion for the above issue mentioned?
Kindly help.

Thanks,
Vithu

**Comment by nikulkarni** [comment]
Is AATT running on port 80 on your localhost?

**Comment by nanthakumarv** [comment]
hi @nikulkarni ,

i hosted the node app.js from the AATT repository and tried hitting the http://127.0.0.1:80 from the browser.

I am able to see the AATT running. And also i am able to  test for accessibility using the page source. Please see the screenshot below:

![aatt-working](https://cloud.githubusercontent.com/assets/20418065/24285249/4691c394-1095-11e7-9098-45b9e04a4890.png)

Is there a demo video on setting up this automation script? That would be really helpful.

Thanks in advance,
Vithu

**Comment by nanthakumarv** [comment]
hi @mpnkhan , @nikulkarni ,

When using large pagesources we are getting an error as below. Only few pages with less amount of page source size, accessibility results are generated.

C:\Users\391533\AATT>node app.js
**Error: spawn ENAMETOOLONG**
    at exports._errnoException (util.js:949:11)
    at ChildProcess.spawn (internal/child_process.js:302:11)
    at exports.spawn (child_process.js:367:9)
    at Object.exports.execFile (child_process.js:139:15)
    at C:\Users\391533\AATT\app.js:149:17
    at Layer.handle [as handle_request] (C:\Users\391533\AATT\node_modules\expre
ss\lib\router\layer.js:82:5)
    at next (C:\Users\391533\AATT\node_modules\express\lib\router\route.js:100:1
3)
    at Route.dispatch (C:\Users\391533\AATT\node_modules\express\lib\router\rout
e.js:81:3)
    at Layer.handle [as handle_request] (C:\Users\391533\AATT\node_modules\expre
ss\lib\router\layer.js:82:5)
    at C:\Users\391533\AATT\node_modules\express\lib\router\index.js:233:24

Most of our application pages have large pagesources and we face this issue many times. Can you please let us know on how to overcome this? Please help.
Thanks,
Vithushini

**Comment by nikulkarni** [comment]
@nanthakumarv It sounds like `socket error hangup` error is now gone? I would like to see below, 
1. `nemo-accessibility` section in config.json 
2.  nemo and browsers (firefox, chrome) versions. I hope you have those setup correctly because without the ability to launch apps, accessibility plugin won't be able to do much
3. When you run the test in a browser like Firefox and Chrome, do you see your application being launched?

**Comment by usabilitykitty** [comment]
@nikulkarni @mpnkhan

Just dropping in to report the same error as @nanthakumarv with longer pages using the included example usingNemoAccessibility.js test. I have tried to run the example test using the home pages for PayPal, Google, and a local development site. Only a brief page (such as https://github.com/about) will generate a report without an error. I am running AATT from localhost:3000.

My nemo-plugins.json file in AATT/config is as follows:
```
"nemo-accessibility":{
  "module":"nemo-accessibility",
  "arguments": ["http://localhost:3000/evaluate"]
}
```

My config.json in AATT/node_modules/nemo-accessibility/config is as follows:
```
{
  "driver": {
    "browser": "chrome"
  },
  "plugins": {
    "nemo-accessibility": {
      "module": "path:../",
      "arguments": ["http://localhost:3000/evaluate"]
    }
  }
}
```
(With the current documentation, I was a little unclear as to where I needed to include my nemo-plugins.json file and which config.json file needed the plugin details. I realize this may be part of my problem. Does this information need to go in the AATT project or the nemo/nemo-accessibilty projects?)

I am using Chrome 57 with ChromeDriver 2.29 and nemo 1.1.2. Chrome successfully launches and navigates to the website. It also logs the accessibility report in the console, but for longer pages, it displays the following in the console without generating an HTML page report:

```
Error: spawn ENAMETOOLONG
    at exports._errnoException (util.js:1026:11)
    at ChildProcess.spawn (internal/child_process.js:313:11)
    at exports.spawn (child_process.js:380:9)
    at Object.exports.execFile (child_process.js:143:15)
    at C:\Users\mswithen\Documents\AATT\app.js:207:17
    at Layer.handle [as handle_request] (C:\Users\mswithen\Documents\AATT\node_m
odules\express\lib\router\layer.js:82:5)
    at next (C:\Users\mswithen\Documents\AATT\node_modules\express\lib\router\ro
ute.js:100:13)
    at Route.dispatch (C:\Users\mswithen\Documents\AATT\node_modules\express\lib
\router\route.js:81:3)
    at Layer.handle [as handle_request] (C:\Users\mswithen\Documents\AATT\node_m
odules\express\lib\router\layer.js:82:5)
    at C:\Users\mswithen\Documents\AATT\node_modules\express\lib\router\index.js
:233:24
```

Please advise. Thank you for your time.

**Comment by nikulkarni** [comment]
@mswithenbank Is this error in AATT or in nemo-accessibility? Also I just published a new version of nemo-accessibility@2.0.0, which uses nemo 2.0. Previous version of nemo and nemo-accessibility were incopmpatible on the latest version of node

**Comment by nanthakumarv** [comment]
hi @nikulkarni ,

Thanks a lot reports are getting populated now :+1: with the new updated you put . Able to automate pages with less amount of pagesource.

But problem is that when the pageSource is larger, the socket hangs and no results are produced. 

In our applications, for few pages, scanning is working and for other pages with large page source socket hangs and the scanning does not happen. the below is the error displayed.

nemo:log Setup complete +1ms
Nemo initialized successfully
  nemo-accessibility:log Now scanning with error level  1,2,3 +0ms
  nemo-accessibility:log Accessibility url  http://127.0.0.1:80/evaluate +1ms
  nemo-accessibility:error Error: socket hang up
  nemo-accessibility:error     at createHangUpError (_http_client.js:250:15)
  nemo-accessibility:error     at Socket.socketOnEnd (_http_client.js:342:23)
  nemo-accessibility:error     at emitNone (events.js:91:20)
  nemo-accessibility:error     at Socket.emit (events.js:185:7)
  nemo-accessibility:error     at endReadableNT (_stream_readable.js:926:12)
  nemo-accessibility:error     at _combinedTickCallback (internal/process/next_t
ick.js:74:11)
  nemo-accessibility:error     at process._tickCallback (internal/process/next_t
ick.js:98:9) +2m

Could be really helpful if you could help out with this.

Thanks,
Vithu

**Comment by mpnkhan** [comment]
Try with axe as engine.

**Comment by nanthakumarv** [comment]
thanks @mpnkhan , its working with the axe engine, but is there a way where we can get the report as how we got while using htmlcs engine, because the report from htmlcs is more understandable and easier to locate the error in code when compared to axe engine and even the number of errors reported is less in axe engine than in htmlcs.

In my options, i have given just this:  var options = {
      'engine': 'axe'
    };

HtmlCS report looks like this:
![image](https://cloud.githubusercontent.com/assets/20418065/25438813/2f445dfe-2ab8-11e7-994d-ca3c84f473f5.png)

Axe engine report for the same page looks like this, unable to locate the html code where the error actually is:
![image](https://cloud.githubusercontent.com/assets/20418065/25438854/49b44f82-2ab8-11e7-8f22-45c5301b97c8.png)

**Comment by mpnkhan** [comment]
This is resolved long back
