### ISSUE TITLE
Report is generated in JSON format

### ISSUE THREAD

**Issue by amazingSpacewafflez** [paypal/nemo-accessibility#22]
Hello,

It looks like I have set everything up but regardless of settings (engine, output, etc.) getting output report in JSON format.

Below are some of my configurations.

**config.json**

  "driver": {
    "browser": "chrome"
  },
  "plugins": {
    "nemo-accessibility": {
      "module": "path:../",
      "arguments": [
        {
          "accessibilityApiUrl" : "http://localhost:3000/evaluate",
          "engine":"axe"  //          axe, chrome, htmlcs
        }
      ]
    },
    "view": {
      "module": "nemo-view",
      "arguments": ["path:../locator"]
    }
  }
}  

**package.json**

{
  "name": "nemo-accessibility",
  "version": "4.0.0",
  "dependencies": {
    "nconf": "^0.10.0",
    "nemo": "^2.0.0",
    "nemo-core": "^1.1.0",
    "nemo-view": "^3.1.0",
    "request": "^2.88.0"
  },
  "main": "index.js",
  "directories": {
    "test": "test"
  },
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/paypal/nemo-accessibility.git"
  },
  "keywords": [
    "nemo",
    "accessibility",
    "plugins",
    "paet"
  ],
  "author": [
    "Nilesh Kulkarni <nikulkarni@paypal.com>",
    "Prem Nawaz Khan <mpnkhan@hotmail.com>"
  ],
  "license": "MIT",
  "devDependencies": {
    "debug": "^4.1.1",
    "nemo-accessibility": "^4.0.0"
  }
}

**dynamicpage.js**
var Nemo = require('nemo');
var fs = require('fs');
var debug = require("debug"),
  log = debug("nemo-accessibility:log"),
  error = debug("nemo-accessibility:error");

var url = 'http://localhost/test/bs_modal_dynamic/donate.html';

var nemo =  Nemo(process.cwd()+'/example',function(err){
  if(!err) {
    nemo.driver.get(url);
    log('Testing url: ' + url)

    var options = {
      'engine' : 'axe'
    };        
    nemo.accessibility.scan(options).then(function (result) {
        var file = process.cwd() + '/example/report/entirePage.html';
        fs.writeFile(file, result,function (err) {
           console.log('Successfully wrote the file ' + file);
        });
    });

    var btn= nemo.view._find('css:#btnDonate');    
    var scanElement= nemo.view._find('css:#myModal');    

    btn.click();
    nemo.driver.sleep(2000);  //Just to show the form for some time

    var options = {
            'source': 'btnDonate',
            'element': scanElement,
            'engine' : 'axe'
        };
    nemo.accessibility.scan(options).then(function (result) {
        var file = process.cwd() + '/example/report/scanAnElement.html';
        fs.writeFile(file, result, function (err) {
            console.log('Successfully wrote the file ' + file);
        });
    });

    nemo.driver.quit();
  } else {
    console.log(err);
  }
});

But upon running getting results in following format

{"results":[{"id":"landmark-one-main","description":"Ensures the page has only one main landmark and each iframe in the page has at most one main landmark","help":"Page must have one main landmark","impact":"moderate"},{"id":"meta-viewport","description":"Ensures does not disable text scaling and zooming","help":"Zooming and scaling must not be disabled","impact":"critical"},{"id":"region","description":"Ensures all page content is contained by landmarks","help":"All page content must be contained by landmarks","impact":"moderate"}]}

**Am I missing something in configuration?**

**Comment by mpnkhan** [comment]
Updated commit 38c5d0fd90b59bc3899742eff1a4d87428fb35d7 with example. We had removed it because, users started parsing json with templating engines like handlebars and dust. Added an example with config change and for now it will work only with axe engine. 
result.results should contain html..
